@echo off

Song by Bryant Oden. Video by Forrest Whaley.Get the song...
http://itunes.apple.com/us/album/the-...

Get the shirt...
https://teespring.com/stores/forrestf...

Thanks so much for watching and sharing! :)
______________________________________________

MORE DUCK SONGS:
http://www.youtube.com/view_play_list...

OTHER SONGS:
http://www.youtube.com/songdrops
Filmy źródłoweGet the song...
http://itunes.apple.com/us/album/the-...

Get the shirt...
https://teespring.com/stores/forrestf...

Thanks so much for watching and sharing! :)
______________________________________________

MORE DUCK SONGS:
http://www.youtube.com/view_play_list...

OTHER SONGS:
http://www.youtube.com/songdrops
Filmy źródłowe
On Error - VBScript - SS64.comss64.com › onerror
Tłumaczenie strony
On Error. Error handling in VBScript is very basic, there is no option to immediately branch to an error handling routine. VBScript does not support GoTo or labels ...

VBScript -- Using error handling - Stack Overflowstackoverflow.com › questions › vb...
Tłumaczenie strony
28 kwi 2015 — VBScript has no notion of throwing or catching exceptions, but the runtime provides a global Err object that contains the results of the last ...
4 odpowiedzi
Understanding ON ERROR in VBScript
3 odpowiedzi
20 cze 2014
How to handle errors in VBS
2 odpowiedzi
7 wrz 2014
Error handling in VBscript
1 odpowiedź
22 lip 2017
returning error code to VBScript
3 odpowiedzi
9 sty 2017
Więcej wyników z stackoverflow.com

Error Handling - VBScript in a Nutshell [Book] - O'Reillywww.oreilly.com › library › view
Tłumaczenie strony
Ordinarily, all runtime errors that are generated by the VBScript engine are fatal, since execution of the current script is halted when the error occurs. Error handling ...

VBScript Error Handling: VBScript On Error, On Error GoTo 0 ...www.softwaretestinghelp.com › vbs...
Tłumaczenie strony
13 wrz 2020 — Error Handling is a very useful mechanism of programming languages like VBScript in order to deal with the errors and to continue the execution ...

Error Handling with VBScript - Rhino Developer Docsdeveloper.rhino3d.com › rhinoscript
Tłumaczenie strony
5 gru 2018 — Overview. There are two statements that affect error handling in VBScript: 1 2 On Error Resume Next On Error Goto 0. The meaning of the first ...

VBScript Err Objects with VBScript - Rhino Developer Docsdeveloper.rhino3d.com › rhinoscript
Tłumaczenie strony
Przejdź do sekcji Using On Error — Overview. The VBScript Err object provides access to run-time error information. The Err object encapsulates errors for a ...

VBScript - Error Handling - Tutorialspointwww.tutorialspoint.com › vbscript
Tłumaczenie strony
VBScript - Error Handling · Syntax errors Syntax errors, also called parsing errors, occur at interpretation time for VBScript. · Runtime errors Runtime errors, also ...

VBScript - On Error Statement - VbsEditwww.vbsedit.com › html
Tłumaczenie strony
If you don't use an On Error Resume Next statement anywhere in your code, any run-time error that occurs can cause an error message to be displayed and ...
1	
2
3
4
5
6
7
8
9
10
Następna
PolskaKcynia - Na podstawie Twojej wcześniejszej aktywności - Użyj dokładnej lokalizacji - Dowiedz się więcej
PomocPrześlij opinięPrywatnośćWarunkiGet our latest mobile game!
Apple - https://tinyurl.com/dumbwaysapple
Google Play - https://tinyurl.com/dumbwaysandroid

Download the song: https://itunes.apple.com/gb/album/dum...
or http://soundcloud.com/tangerinekitty/...

Find us on Facebook:
‪https://www.facebook.com/dumbwaystodie‬

© Metro Trains Melbourne, Dumb Ways to Die™

hallo
-ShiningStar-
scratch code
United States
5 recent friends
BEXtraordinaryBEXtraordinary
nekomikunekomiku
ThatOneJoodThatOneJood
chiharuchiharu
Ninja_Star96Ninja_Star96
See more
Galleries
-ShiningStar- has not created any Galleries
See more
-ShiningStar-'s Projects
 Subscribe
Me as Fruit
Me as Fruit
Comments: 11

Kiwi&amp;Mango
Kiwi&Mango
Comments: 0

A new way to color eyes!
A new way to colo…
Comments: 15

artandsketchesofpossiblefutureart
artandsketchesofp…
Comments: 19

Matryoshka
Matryoshka
Comments: 3

heyheyhey
heyheyhey
Comments: 7

!!!
!!!
Comments: 27

Carnival Games!
Carnival Games!
Comments: 22

Eye Blinking Tutorial~
Eye Blinking Tuto…
Comments: 25

Pen Generator Thingy.
Pen Generator Thi…
Comments: 23

RANDOM GENERATOR.
RANDOM GENERATOR.…
Comments: 77

BIRTHDAY
BIRTHDAY
Comments: 53

Water test
Water test
Comments: 32

Another Pointless Project. :|
Another Pointless…
Comments: 9

Update! + A song I wrote!
Update! + A song …
Comments: 36

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
-ShiningStar-'s Favorites
YES. I MADE A STORY. READ OR DIE.
YES. I MADE A STO…
by bookworm778

Easy Game Creator 1.1
Easy Game Creator…
by ROSMan

Webbing pen: 2.0
Webbing pen: 2.0
by bobo1121212

Dress up chibi girl
Dress up chibi gi…
by chocomax

Shiny's Hair Salon
Shiny's Hair Salo…
by -ShiningStar-

LOVE &lt;3
LOVE <3
by MangoChan

Style Exercises Meme
Style Exercises M…
by 4485

Shadows Breach Episode 1
Shadows Breach Ep…
by Jaiku

Hand tutorial
Hand tutorial
by ninja_Otaku96

Doctor Kill-ter
Doctor Kill-ter
by OffKilter

test wmd003
test wmd003
by JTxt

The Taco Incident - Part 1 (DOWNLOAD)
The Taco Incident…
by jonzo

Vocaloid Dating Game-WIP
Vocaloid Dating G…
by -ShiningStar-

How to draw anime~!
How to draw anime…
by the-real-kira

ruddy the red nose reindeer
ruddy the red nos…
by white_kitty_r…

1 | 2 | 3 | 4
PL
WINDOWS SOVIET EDITION 2!




2

Awatar


0:57 / 3:01

Dumb Ways to Die
198 169 144 wyświetlenia•15 lis 2012

1,8 MLN

66 TYS.

UDOSTĘPNIJ

ZAPISZ


DumbWays2Die
878 tys. subskrypcji
Get our latest mobile game!
Apple - https://tinyurl.com/dumbwaysapple
Google Play - https://tinyurl.com/dumbwaysandroid

Download the song: https://itunes.apple.com/gb/album/dum...
or http://soundcloud.com/tangerinekitty/...

Find us on Facebook:
‪https://www.facebook.com/dumbwaystodie‬

© Metro Trains Melbourne, Dumb Ways to Die™
144 421 komentarzy
Hubert Chudzik
Dodaj publiczny komentarz...
aksually
aksually
2 miesiące temu
these are some real dumb ways to die

11 tys.


Mochii Bruv
Mochii Bruv
6 dni temu
Another dumb way to die:

Take off your mask in a crowded store

838


The Broadcaster
The Broadcaster
2 tygodnie temu (edytowany)
This is a very smart way to teach people about train safety that’s kinda an obscure fact that Dumb ways to die is a campaign from metro that teaches about train safety but it’s a smart way to do it

685


Ley_Ley _Official
Ley_Ley _Official
2 tygodnie temu
This song accidentally thought me how to avoid death.

325


Bossome
Bossome
2 tygodnie temu
1:47 that one guy in among us literally 2 seconds after the game starts

834


ItsGavin
ItsGavin
3 miesiące temu
this isn’t in our recommended, we chose to come back

6,9 tys.


SKITZ GAMING
SKITZ GAMING
1 tydzień temu (edytowany)
Fun fact: This game was made by the government.

248


yo -
yo -
2 tygodnie temu (edytowany)
Since no one else gonna do it, here’s the lyrics for people coming back to sing along:

Set fire to your hair
Poke a stick at a grizzly bear
Eat medicine that's out of date
Use your private parts as Piranha bait
Dumb ways to die
So many dumb ways to die
Dumb ways to die-ie-ie
So many dumb ways to die
Get your toast out with a fork
Do your own electrical work
Teach your self how to fly
Eat a two-week-old unrefridgerated pie
Dumb ways to die
So many dumb ways to die
Dumb ways to die-ie-ie
So many dumb ways to die
Invite a psycho killer inside
Scratch a drug dealer's brand new ride
Take your helmet off in outer space
Use a clothes dryer as a hiding place
Dumb ways to die
So many dumb ways to die
Dumb ways to die-ie-ie
So many dumb ways to die
Keep a rattle snake as a pet
Sell both your kidneys on the internet
Eat a tube of super glue
I wonder, what's this red button do?
Dumb ways to die
So many dumb ways to die
Dumb ways to die-ie-ie
So many dumb ways to die
Dress up like a moose during hunting season
Disturb a nest of wasps for no good reason
Stand on the edge of a train station platform
Drive around the boom gates at a level crossing
Run across the tracks between the platforms
They may not rhyme, but they're quite possibly
Dumbest ways to die
The dumbest ways to die
Dumbest ways to die-ie-ie
So many dumb
So many dumb ways to die

996


Ninja Warrior
Ninja Warrior
1 tydzień temu
“MOM MOM MOM”
“What”
“WE CAN BE RICH”
“How Sweetie”
“Sell both my kidneys”
Mom: 👁👄👁

642


Katie Amerio The Second
Katie Amerio The Second
1 tydzień temu
If you are watching this today...

You get a Nostalgia Ticket to "It's Raining Tacos"

216


BRPNO
BRPNO
5 miesięcy temu
After 7 years, I still can’t believe this whole thing was just a message telling you to be careful around trains

12 tys.


GamergirlAsh 98
GamergirlAsh 98
6 dni temu
Title: dumb ways to die 
197 million people: oooh what does this button do

160


bing bong
bing bong
1 tydzień temu
another dumb ways to die:
doing electrical tasks alone in among us

221


Sara Saliba
Sara Saliba
2 tygodnie temu (edytowany)
People who want to end it.


“WRITE THAT DOWN, WRITE THAT DOWN!”

Guys if you’re thinking about it don’t please, you’ll regret it. Love y’all! ❤️

317


Greg Ford
Greg Ford
1 tydzień temu
2012: Colorful Beans


2020: Colorful Beans

88


BluwZen
BluwZen
6 miesięcy temu
the memories of taking moms phone to play this in the restaurant while waiting for the table to be available

10 tys.


Neighborhood Gang
Neighborhood Gang
1 tydzień temu
“Sell both kidneys on the internet”
 Little did they know...I have four kidneys

34


VxnillA Cvpcakez
VxnillA Cvpcakez
2 tygodnie temu
If you didn’t ever in your life play this game I don’t know if you have a childhood









No hate it’s just facts✨

187


Big Meaty Claws
Big Meaty Claws
2 tygodnie temu (edytowany)
man, this is too dark for kids...




whatever i loved it

85


Samantha Prescott
Samantha Prescott
2 tygodnie temu
If this never existed, then I would be the annoying kid you see in class. (No offense to anyone)

95


『 KxramelCxke 』
『 KxramelCxke 』
1 miesiąc temu
“We didn’t realize we were making memories, we just knew we were having fun”

 -Winnie the Pooh

4,8 tys.


? ?UnKnOwN
? ?UnKnOwN
2 tygodnie temu
if you didn’t get this song stuck in your head every time someone said “Die” or “Dumb” then you’re doing something wrong!

77


*_* Carmatiny
*_* Carmatiny
2 tygodnie temu
The fact that there are comments from minutes ago just shows how nostalgic, iconic and educational this song is

34


SuperSquid 004
SuperSquid 004
2 tygodnie temu
0:10
DEAD BODY REPORTED
DISCUSS!!!
Me:ngl bear's kinda sus

125


RadMelxdy
RadMelxdy
2 tygodnie temu
screw it... i’m going back to my childhood where my only worry was my Minecraft dog-

60


mria daniela
mria daniela
6 miesięcy temu
who else is proud to say that this was part of their childhood? ❤️

29 tys.


HIGJIG_YT
HIGJIG_YT
2 tygodnie temu
Remember when there wasn’t adds every 2 rounds

35


Danah Alsaffar
Danah Alsaffar
2 tygodnie temu
I’m crying because this has so many memories I played this since kindergarten and this game was so much fun!

23


Rom The goat
Rom The goat
5 dni temu
THIS SONG BRINGS BACK SO MANY MEMORIES, I remember going to my friends house just so I could play that game, then she showed me the song and a month later for my birthday  my mother bought a tablet for me so I downloaded the game and it’s been 6 years since I’ve downloaded it....and I still play it

7


• Antu •
• Antu •
1 tydzień temu
Fun fact :
You still don't know why
Your parents let you watch this
Or download the app.

13


Yxlesi
Yxlesi
3 miesiące temu
This song has been stuck somewhere in my brain for 4 years now, it comes back every week
and I have returned

908


Mattiside
Mattiside
1 dzień temu (edytowany)
Another dumb way to die: participate in a protest

1


The Litt Family
The Litt Family
1 tydzień temu
Who’s here in 2020 I am 💖❤️

5


Nightbot t
Nightbot t
1 dzień temu
Go outside without a mask.

Shake a hand, before you ask.

Gather around, 
with people you found.

Stop trusting medical workers with the cases that they count.

Dumbbb ways to die! Some really dumb ways to die...

2


Jackson
Jackson
5 dni temu
Fun fact: Everyone who died in this had a name

4


ღKiwiLovesKiwi シ
ღKiwiLovesKiwi シ
1 miesiąc temu
The dislikes are people who found smart ways to die

4 tys.


Bogi Zsóri
Bogi Zsóri
1 tydzień temu
Not gonna lie: we really like this music.

8


Mei
Mei
2 tygodnie temu (edytowany)
Guys I have played this game since I was 6 years old and am now 14, I forgot about it when I was 10, and now have come back to it and I used I watch the video every time I played, so before I played the first thing I did was click the video, because that’s what I always did. This was my favorite thing, and now when I watch the video again, it made me cry only 1 minute in. You’ve come a long way, younger me, and this game. 🥺 I will never forget you again. 😭❤️🥺

10


Justin Reissner
Justin Reissner
1 tydzień temu
that one person at the start of an among us match: 1:47

11


Gabriel Guimarães Cunha
Gabriel Guimarães Cunha
51 minut temu
another dumb way to die: 

do everything that this video said.



nikucis1 1
nikucis1 1
2 miesiące temu
Fun fact: You like this song.

9,9 tys.


JayJay watermelon
JayJay watermelon
1 tydzień temu
I remember my mom telling me not to listen to this song when I was playing the game

5


Pinky Sparkle
Pinky Sparkle
4 dni temu
It is true, there’s many dumb ways to die

6


not me
not me
1 dzień temu
Another dumb way to die:


Go to electrical alone



Emyel Gio
Emyel Gio
4 dni temu
To think that this is a Train commercial is just so good.

5


Starxy Barxy
Starxy Barxy
1 miesiąc temu
POV: your watching this in 2020 because  you want memories

5,9 tys.


Pasky Pascua
Pasky Pascua
1 dzień temu
I wonder why the three people on the end was killed by ONE train...
And she’s voice was like garnet



Cats Are Green
Cats Are Green
1 tydzień temu
It’s so weird that this is basically just a psa about trains

8


737215
737215
2 dni temu
2:40 RIP to purple who gets killed by a train AND by Dumb Ways to Draw thumbnail

3


Shellby
Shellby
1 dzień temu
Why is everyone acting like this was their childhood?



jaiuwu jai
jaiuwu jai
4 miesiące temu (edytowany)
If you're watching this in 2020 you're a living legend.



Oh wow this got likes

16 tys.


2 Subscribers with 1 video challenge !!?!1!1!
2 Subscribers with 1 video challenge !!?!1!1!
17 godzin temu
Feeling bad for the kids who just born

2


Noel R. Elivera Jr.
Noel R. Elivera Jr.
2 tygodnie temu
When i was a kid i thought the Green dude at the start is he ate a medicine that make you a bush

7


samuel Martin
samuel Martin
1 tydzień temu
Dr Dre has been real quiet since this banger dropped

4


Pablo Escobar
Pablo Escobar
40 minut temu
this is extremely offensive to the people who died these ways, they were not dumb



PixelixerPlays
PixelixerPlays
1 miesiąc temu
‘I wonder what this red button do’

- God, 2020

3,4 tys.


Arztech
Arztech
1 dzień temu
Parents: *Overpressure Their Kid*




The Kid:



Kenrick Clark Rulete
Kenrick Clark Rulete
2 dni temu
A new dumb way to die:
Listen to a karen....

3


Goal: 100 Subscribers
Goal: 100 Subscribers
1 dzień temu (edytowany)
My mom yelled at me when I played this in the car to school. It’s because the song says private parts.

1


Zara Teleskivi
Zara Teleskivi
1 tydzień temu
this is when they try to make dying child friendly

3


Następny
AUTOODTWARZANIE

4:28
TERAZ ODTWARZANE
MINECRAFT SKELETON RAP REMIX | "I've Got A Bone" | Oxygen Beats Dan Bull Animated Music Video
Dan Bull

“no sé la cantan unos forros”

1


1k Subs Challenge [Memeologist]
1k Subs Challenge [Memeologist]
2 miesiące temu
2012: "be safe around trains"
2020: "be safe around others"

2,2 tys.


SeasonalAvocado
SeasonalAvocado
5 dni temu
1:47 When we plays Among Us for the 1st time.

3


「 Buttered Macaroons 」
「 Buttered Macaroons 」
2 tygodnie temu
Me, 7 years ago: Haha! They're so dumb if they die like that!

Me, right now: *Literally wishes to die everytime a minor inconvenience occurs*

1


chunts li
chunts li
2 dni temu
1:50

Kim jong-un at the end of WW3.

3


Areen Hashemi
Areen Hashemi
2 dni temu
The earth is 4.6 B years old, and we exist in the same time as this masterpiece



Pickle 124
Pickle 124
2 miesiące temu
I feel bad for people who didn’t know this song existed 😔

2,2 tys.


• Nutella Milk •
• Nutella Milk •
1 dzień temu
I Used To Watch This Every Single Day After School



シJᴀʏʟᴇɴ
シJᴀʏʟᴇɴ
2 tygodnie temu
I freaking grew up with this song it’s so sad to hear it again! Good times!!! ❤️🥺😭😭😭😭💞

4


hydratedd
hydratedd
5 dni temu
For those who played this religiously as children...








How are your intrusive thoughts doing?

16


Kim Gi
Kim Gi
2 tygodnie temu
If this doesn’t get played in my funeral I refuse to die

8


xendurr
xendurr
1 miesiąc temu
This hits different 7 years later.

1,4 tys.


Nicholas Morgan
Nicholas Morgan
3 dni temu
This is karens in a nutshell

5


Lisa's Bangs.
Lisa's Bangs.
9 godzin temu
Who else just wants to go back in time.



Elise 123
Elise 123
2 tygodnie temu
Me: Sees the super glue dude
Also me: Vietnam Flashbacks of always losing at that one

2


MilkiiZoop
MilkiiZoop
1 tydzień temu
If you never played this game when you were younger and didn’t listen to this at least 3 times you didn’t live your childhood correctly

2


NNixon4_
NNixon4_
5 miesięcy temu
Dumb ways to die: largely forgotten                                Quarantine: I’m about to save this apps whole career

2,9 tys.


Qusai Abo harb
Qusai Abo harb
3 dni temu
I woke up out of nowhere singing this song

3


Kaylee Murillo
Kaylee Murillo
2 tygodnie temu (edytowany)
A few month ago I was playing hide and seek with my friends and I hid in the washing machine bc I’m small so I could fit in there and when they found me they said HAVEN’T YOU EVERY PLAYED DUMB WAYS TO DIE and all of the memories came flooding back

2


Psalm Fufugal
Psalm Fufugal
14 godzin temu
POV: you are looking for nostalgia

1


Red Shell
Red Shell
2 tygodnie temu
2012: "Lol this song is funny XD"

2020: "Dear god, this hits different. I want to go back"



VaxzZ
VaxzZ
9 miesięcy temu (edytowany)
who came here because they started singing it randomly

13 tys.


No One
No One
2 tygodnie temu (edytowany)
I remember when this came out and I'd get on a train in Melbourne going to school, I'd sing to people parts of this song and tell them be safe around these trains.

almost every single person knew exactly what I was talking about.

Looking back what's even funnier is we had to make a three minute song about don't fucking die from a train.



DarkHeroYT
DarkHeroYT
1 tydzień temu
I was playing 5 years old,i remember the times:)that i was pressing the button lol

2


The stick Destroyer
The stick Destroyer
2 tygodnie temu
When I was young, I watch this. This is still my legend.

2


Black. I'm just an empty void
Black. I'm just an empty void
4 dni temu
1:14 "green was not the impostor"

4


Niall Jones
Niall Jones
2 miesiące temu (edytowany)
Why is it such a happy song when its about DEATH.











Edit. I dont wanna sound cringey but thx for the likes :}

2,2 tys.


Leena Hafez
Leena Hafez
2 tygodnie temu
this game was literally  my whole childhood and hearing this song brings back so much nostalgia

1


Ethan's Rections
Ethan's Rections
1 dzień temu
There's a reason why there called dumb ways to die but PEOPLE STILL DIE IN DUMB WAYS!!



benedict decent
benedict decent
2 tygodnie temu
Additional lyric :
" Lick an toilet seat for a challenge... DUMB WAYS TO DIEEEE"

1


LuckyShot
LuckyShot
1 tydzień temu
2020 update: not wearing a mask in public spaces

2


James James
James James
3 tygodnie temu (edytowany)
If you’re watching this in 2020 you deserve a veterans discount

2,1 tys.


AJ Aviation
AJ Aviation
1 tydzień temu
Imagine if there was a ‘Dumb Ways To Die- 2020’ I think there would be many more than this...

1


Himiko Yumeno
Himiko Yumeno
12 godzin temu
LMAO I remember playing this and my parents gave me a lecture cause it was "violent"



Nixolas
Nixolas
2 tygodnie temu
Just imagine for a second a crossover in a game between this thing and Happy Tree Friends

1


Not Beans
Not Beans
1 tydzień temu
I used to play this when I was 5 years old and now I’m like 12 but it still seems this was a really long time ago 😢

1


Isabella Gardener
Isabella Gardener
1 rok temu
Kids today will never get how legendary this was

14 tys.


ItzRøyāl Møchii
ItzRøyāl Møchii
1 tydzień temu
I used to listen to this everyday until i played it around my mom and she told me to stop listening to it but I'M BACK ;w;

1


Jami Construction
Jami Construction
2 tygodnie temu
i wonder what does this red button do?

Red button: let me introduce myself

1


Juvenal Camacho
Juvenal Camacho
1 dzień temu (edytowany)
1:47 in among us you press the emergency button but it was actually a bomb button by the imposter and letting the imposter win
Or maybe wen the O2 was sabotaged you found a red button and you press it and explode

Bro there is so many among us in my head!!



Hugo van de kuilen
Hugo van de kuilen
1 tydzień temu
i wonder, was this red bu'on dooow.







oh, it just subscribes, dissapointing (but deserved)

2


Janiya Lewis
Janiya Lewis
2 miesiące temu
"What's your favorite song?"


me: its complicated..

1,1 tys.


David Barcenas
David Barcenas
2 dni temu
u see, This is why i want people safe from dangerous, or harmful things that can happen to people.



Archer Tor
Archer Tor
2 tygodnie temu
i’m literally crying

omggg my favorite gameeeeeee

2


Gree
Gree
2 tygodnie temu
To think this was originally made as an ad campaign for train safety in Melbourne, Australia

2


some random merc
some random merc
2 tygodnie temu (edytowany)
Friend: Search up the Youtube trending page
Me: Okay..
Me: Wow this really is awesome
Teacher: You better not be watching YouTube!



Hika Verse
Hika Verse
2 tygodnie temu
If this isnt playing at my funeral im not coming.

1,5 tys.


Aesthetic_Sapphire
Aesthetic_Sapphire
2 tygodnie temu
Get coughed on by a coronavirus victim without wearing a mask-

2


Aziah
Aziah
2 tygodnie temu
If You Dont Know This Song,Your Childhood Wasnt fun :(,Miss Old Dayss When Life Was Quite Easy.

2


Arianna Manmadhan
Arianna Manmadhan
2 tygodnie temu
I remember this clearly (4 years ago I was 7)
I was at my brothers friends house and we were playing “Dumb ways
To die”. We all sat on one couch and got his (bros friends) iPad. We
Started playing then my toenail started chipping from the top corner
Of the nail. 

Completely random story but whatever

1


Softie
Softie
1 tydzień temu
0:15 me when i was 5 years old and then i went to the adult pool

1


Vurchi
Vurchi
2 miesiące temu
If you didn’t play this game as a child, did you even have a childhood-

1,8 tys.


FluXas PW
FluXas PW
1 tydzień temu
Legends know there's a background voice when the chorus comes.

1


シJᴀʏʟᴇɴ
シJᴀʏʟᴇɴ
2 dni temu
“You could get coronavirus”

1


Indian pewd gang
Indian pewd gang
1 tydzień temu
Cool idea : move out with no masks and check the result

2


Coffee foreva
Coffee foreva
1 tydzień temu
I-


the memories its been a long time since i haven't heard this song ;-;
i miss childhood T-T

1


The_girl_on_ the_streets
The_girl_on_ the_streets
1 miesiąc temu
This song should be played at my funeral

1,7 tys.


Killer Moth XD
Killer Moth XD
1 tydzień temu
Metro: NEVER DO THESE
People on the Dark web: No I don’t think I will



Baji Estremadura
Baji Estremadura
2 tygodnie temu
it's been 7 or 8 year's and i still remember this song [ ; ; ]

1


Yankeeschamber 99
Yankeeschamber 99
2 dni temu
If this doesn't play when I die I am reviving myself.



shaquille_oatmeal
shaquille_oatmeal
4 godziny temu
Damn the memories, I just remember me, my brother, cousin, and friends playing this game.



Woomy Dayz
Woomy Dayz
2 miesiące temu
7 year old me never found this disturbing and played it religiously.

2,2 tys.


Galaxygamer201 :3
Galaxygamer201 :3
3 dni temu
0:10

Among us in a nutshell

3


Bean Mann
Bean Mann
6 dni temu
Bruh I still remember being scared of the no helmet in space thing when I was younger

1


•chanel mpk•
•ch
